# Generated by Django 6.0.2 on 2026-02-26 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='capa',
            field=models.ImageField(blank=True, null=True, upload_to='projetos/'),
        ),
    ]
