# Generated by Django 6.0.2 on 2026-03-04 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_portfolio', '0004_informacoespessoais_cargo_informacoespessoais_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControleDispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispositivo', models.CharField(max_length=50, unique=True)),
                ('mandar_oi', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LeituraAmbiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispositivo', models.CharField(max_length=50)),
                ('temperatura', models.FloatField()),
                ('umidade', models.FloatField()),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
