# Generated by Django 6.0.2 on 2026-03-04 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_portfolio', '0005_controledispositivo_leituraambiente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controledispositivo',
            name='mandar_oi',
        ),
        migrations.AddField(
            model_name='controledispositivo',
            name='quantidade_ois',
            field=models.IntegerField(default=0),
        ),
    ]
